# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20160629_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faq.Post', verbose_name='Привязка к записи'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='faq.Menu', verbose_name='Родительское меню'),
        ),
    ]
