# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_auto_20161005_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentphoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='faq.Comment'),
        ),
    ]
