# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0007_club_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cant_work', models.BooleanField(default=False, verbose_name='Не работаем')),
                ('probation', models.BooleanField(default=False, verbose_name='Стажер')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.CharField(default='00:00', max_length=6, verbose_name='Время начала')),
                ('end_time', models.CharField(default='00:00', max_length=6, verbose_name='Время окончания')),
                ('comment', models.TextField(blank=True, verbose_name='Дополнительно')),
                ('probation', models.BooleanField(default=False, verbose_name='Стажировка')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='Клуб')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_calendar.EmployeeInCalendar', verbose_name='Сотрудник')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
