# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_calendar', '0003_auto_20160612_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeincalendar',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeInCalendar',
        ),
    ]
