# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_calendar', '0004_auto_20160615_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
