# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_calendar', '0005_auto_20160717_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='cant_work_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина почему не может работать'),
        ),
    ]
