# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20160603_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID из старой системы'),
        ),
    ]
