# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0007_club_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_time', models.CharField(default='--:--', max_length=6, verbose_name='Время начала работы')),
                ('end_time', models.CharField(default='--:--', max_length=6, verbose_name='Время начала работы')),
                ('date', models.DateField(verbose_name='Дата')),
                ('shots_count', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Количество шотов')),
                ('sum_for_bar', models.IntegerField(blank=True, verbose_name='Сумма в бар')),
                ('discount', models.IntegerField(blank=True, verbose_name='Сумма скидки')),
                ('comment', models.TextField(blank=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='Заведение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
