# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_calendar', '0004_auto_20160615_1731'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='club',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='employee',
        ),
        migrations.AddField(
            model_name='report',
            name='work_shift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='work_calendar.WorkShift', verbose_name='Рабочая смена'),
            preserve_default=False,
        ),
    ]
