# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160615_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='shots_count',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Количество шотов'),
        ),
    ]
