# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160615_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.CharField(blank=True, max_length=6, verbose_name='Время начала работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.CharField(blank=True, max_length=6, verbose_name='Время начала работы'),
        ),
    ]
