# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_city'),
        ('reports', '0005_auto_20160616_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Drink', verbose_name='Напиток')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='reports.Report', verbose_name='Отчет')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
