# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdrink',
            name='count',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Количество'),
        ),
    ]
