# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20160621_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='shots_count',
        ),
    ]
