# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0010_remove_report_shots_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ТОЧНАЯ СУММА ПЕРЕВОДА (до копеек) С УЧЕТОВ ШТРАФОВ, ЗАЛОГОВ, ДОЛГОВ и т.д.')),
                ('transfer_type', models.TextField(blank=True, verbose_name='Способ перевода')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('start_week', models.DateField(verbose_name='Дата начала недели за которую написан перевод')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
