# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reporttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttransfer',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Оплату подтверждаю'),
        ),
    ]
