# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_reporttransfer_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttransfer',
            name='transfer_type',
        ),
    ]
