# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_remove_reporttransfer_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdrink',
            name='price_for_sale',
            field=models.IntegerField(default=0, verbose_name='Цена продажи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportdrink',
            name='price_in_bar',
            field=models.IntegerField(default=0, verbose_name='Цена в баре'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='work_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='work_calendar.WorkShift', verbose_name='Рабочая смена'),
        ),
    ]
