# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='time',
            field=models.CharField(choices=[('both', 'Вечер и ночь'), ('night', 'Ночь'), ('evening', 'Вечер')], default='both', max_length=8, verbose_name='Время работы'),
        ),
    ]
