# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import private_message.models


class Migration(migrations.Migration):

    dependencies = [
        ('private_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesformessage',
            name='file',
            field=models.FileField(upload_to=private_message.models.FilesForMessage.get_upload_path, verbose_name='Файл'),
        ),
    ]
