# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_message', '0002_auto_20160721_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_transfered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filesformessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='private_message.Message'),
        ),
    ]
