# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0008_auto_20160630_1759'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPenaltySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('schedule', 'График'), ('report', 'Отчеты')], max_length=10, verbose_name='Тип')),
                ('start_week', models.DateField(blank=True, null=True, verbose_name='Дата начала недели за которую написан перевод')),
                ('day_of_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.DayOfWeek', verbose_name='День недели')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Дата')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tequilla girl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenaltyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('num', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('dismissal', models.BooleanField(default=False, verbose_name='Возможно увольнение')),
            ],
            options={
                'ordering': ('num',),
            },
        ),
        migrations.AddField(
            model_name='penalty',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penalty.PenaltyType', verbose_name='Тип штрафа'),
        ),
    ]
