# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty', '0002_auto_20160702_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='was_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
