# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty', '0003_penalty_was_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpenaltyschedule',
            name='is_acitve',
            field=models.BooleanField(default=False, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='mainpenaltyschedule',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время проверки'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='was_paid',
            field=models.BooleanField(default=False, verbose_name='Штраф был оплачен'),
        ),
    ]
