# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalty', '0004_auto_20160730_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpenaltyschedule',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
