# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkforstate',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество шотов'),
        ),
        migrations.AddField(
            model_name='drinkforstate',
            name='type',
            field=models.CharField(choices=[('shot', 'Шот'), ('beaker', 'Мензурка')], default='beaker', max_length=10),
        ),
        migrations.AlterField(
            model_name='drinkforstate',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем мензурок'),
        ),
    ]
