# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20160804_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorstate',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма скидки'),
        ),
    ]
