# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_calculatorstate_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorstate',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма скидки'),
        ),
    ]
