# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uniform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformByWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('start_week', models.DateField(verbose_name='Дата начала недели за которую проставляется количество формы')),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniform.Uniform', verbose_name='Атрибут')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniformForEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_probation', models.BooleanField(default=False, verbose_name='Стажировка')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tequilla girl')),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniform.Uniform', verbose_name='Атрибут')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
