# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uniform', '0002_uniformbyweek_uniformforemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformTransferByWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('start_week', models.DateField(verbose_name='Дата начала недели за которую проставляется перевод')),
                ('was_paid', models.BooleanField(default=False, verbose_name='Перевод')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tequilla girl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='uniform',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
