# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0003_auto_20160706_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformtransferbyweek',
            name='sum',
        ),
    ]
