# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0005_auto_20160725_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformtransferbyweek',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='Наличными'),
        ),
        migrations.AddField(
            model_name='uniformtransferbyweek',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='uniformtransferbyweek',
            name='uniform_for_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='uniform.UniformForEmployee'),
        ),
    ]
