# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0006_auto_20160801_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformbyweek',
            name='who',
            field=models.CharField(choices=[('coordinator', 'Координатор'), ('chief', 'Руководитель')], default='chief', max_length=15, verbose_name='Чей план'),
        ),
        migrations.AddField(
            model_name='uniformforemployee',
            name='who',
            field=models.CharField(choices=[('coordinator', 'Координатор'), ('chief', 'Руководитель')], default='chief', max_length=15, verbose_name='Кто выдал форму'),
        ),
    ]
