# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0007_auto_20160809_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformtransferbyweek',
            name='employee',
        ),
        migrations.AddField(
            model_name='uniformforemployee',
            name='group',
            field=models.PositiveIntegerField(default=0, verbose_name='Группировка'),
            preserve_default=False,
        ),
    ]
