# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0008_auto_20160813_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformtransferbyweek',
            name='uniform_for_employee',
        ),
        migrations.AddField(
            model_name='uniformtransferbyweek',
            name='group',
            field=models.PositiveIntegerField(default=1, verbose_name='Группировка'),
            preserve_default=False,
        ),
    ]
