# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 07:37
from __future__ import unicode_literals

import club.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('old_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID из старой системы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('site', models.CharField(max_length=255, verbose_name='Сайт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Особенности')),
                ('discount_conditions', models.TextField(blank=True, null=True, verbose_name='Условия скидки')),
                ('drinks', models.TextField(blank=True, null=True, verbose_name='Напитки')),
                ('count_shots', models.CharField(blank=True, max_length=255, null=True, verbose_name='Норма шотов')),
                ('start_time', models.CharField(default='00:00', max_length=6, verbose_name='Время начала работы')),
                ('end_time', models.CharField(default='00:00', max_length=6, verbose_name='Время окончания работы')),
                ('w_start_time', models.CharField(default='00:00', max_length=6, verbose_name='Время начала работы на выходных')),
                ('w_end_time', models.CharField(default='00:00', max_length=6, verbose_name='Время окончания работы на выходных')),
                ('contact_person', models.TextField(blank=True, null=True, verbose_name='Контактное лицо')),
                ('rate', models.CharField(default='0', max_length=5, verbose_name='Рейтинг')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Координатор')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('old_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID из старой системы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('short_name', models.CharField(max_length=3, verbose_name='Короткое название')),
                ('num', models.PositiveSmallIntegerField(verbose_name='Номер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('old_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID из старой системы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.ImageField(upload_to=club.models.Photo.get_upload_path, verbose_name='Изображение')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('old_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID из старой системы')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='club.Club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='club',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, to='club.DayOfWeek', verbose_name='Дни недели'),
        ),
        migrations.AddField(
            model_name='club',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='club',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Metro'),
        ),
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.ManyToManyField(blank=True, to='club.ClubType', verbose_name='Тип заведения'),
        ),
    ]
