# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:36
from __future__ import unicode_literals

from django.db import migrations


def init_days_of_week(apps, schema_editor):
    DayOfWeek = apps.get_model("club", "DayOfWeek")
    DayOfWeek.objects.create(num=1, name='Понедельник', short_name='Пн')
    DayOfWeek.objects.create(num=2, name='Вторник', short_name='Вт')
    DayOfWeek.objects.create(num=3, name='Среда', short_name='Ср')
    DayOfWeek.objects.create(num=4, name='Четверг', short_name='Чт')
    DayOfWeek.objects.create(num=5, name='Пятница', short_name='Пт')
    DayOfWeek.objects.create(num=6, name='Суббота', short_name='Сб')
    DayOfWeek.objects.create(num=7, name='Воскресенье', short_name='Вс')


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_days_of_week),
    ]
