# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20160528_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Координатор'),
        ),
    ]
