# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20160529_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price_in_bar', models.IntegerField(verbose_name='Цена в баре')),
                ('price_for_sale', models.IntegerField(verbose_name='Цена продажи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='club',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Metro', verbose_name='Станция метро'),
        ),
        migrations.AddField(
            model_name='drink',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='Заведение'),
        ),
    ]
