# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20160606_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сайт'),
        ),
    ]
