# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 16:28
from __future__ import unicode_literals

from django.db import migrations


def add_cities(apps, schema_editor):
    City = apps.get_model("club", "City")
    City.objects.get_or_create(name='Москва')
    City.objects.get_or_create(name='Санкт-Петербург')


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20160606_1615'),
    ]

    operations = [
        migrations.RunPython(add_cities),
    ]
