# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metro',
            options={'ordering': ('name',)},
        ),
    ]
