# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_auto_20160807_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='discount_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер скидки (используется в калькуляторе)'),
        ),
    ]
