# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_auto_20160812_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='markup',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 - 70'), (75, '75 - 125')], default=75, verbose_name='Наценка (используется в калькуляторе)'),
        ),
        migrations.AlterField(
            model_name='club',
            name='equal_prices',
            field=models.BooleanField(default=False, verbose_name='Цена продажи равна цене в баре (для калькулятора)'),
        ),
        migrations.AlterField(
            model_name='club',
            name='formula',
            field=models.CharField(choices=[('beaker', 'Для мензурки'), ('shot', 'Для шотов')], default='shot', max_length=10, verbose_name='Формула рассчета (для ведомости)'),
        ),
    ]
