# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_club_additional_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='without_discount',
            field=models.BooleanField(default=False, verbose_name='Скидку не делают (наценка/2 * кол. шотов)'),
        ),
    ]
