# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_plan', '0002_auto_20160718_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planforday',
            name='work_shift',
        ),
        migrations.AddField(
            model_name='planforday',
            name='who',
            field=models.CharField(choices=[('coordinator', 'Координатор'), ('chief', 'Руководитель')], default='chief', max_length=15, verbose_name='Чей план'),
        ),
    ]
