# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:44
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType


def init_permissions(apps, schema_editor):
    ExtUser = apps.get_model("extuser", "ExtUser")
    ct = ContentType.objects.get_for_model(ExtUser)

    pay_wages_permission, created = Permission.objects.get_or_create(
        codename='can_pay_wages', name='Выдача зарплаты', content_type=ct
    )
    edit_fines_permission, created = Permission.objects.get_or_create(
        codename='can_edit_fines', name='Редактирование штрафов', content_type=ct
    )
    see_statistics_permission, created = Permission.objects.get_or_create(
        codename='can_see_statistics', name='Просмотр статистики', content_type=ct
    )
    edit_clubs_permission, created = Permission.objects.get_or_create(
        codename='can_edit_clubs', name='Редактирование клубов', content_type=ct
    )
    edit_users_permission, created = Permission.objects.get_or_create(
        codename='can_edit_users', name='Редактирование сотрудников', content_type=ct
    )
    edit_posts_permission, created = Permission.objects.get_or_create(
        codename='can_edit_posts', name='Редактирование статей', content_type=ct
    )

    director_group, created = Group.objects.get_or_create(name='director')

    director_group.permissions = [
        pay_wages_permission,
        edit_fines_permission,
        see_statistics_permission,
        edit_clubs_permission,
        edit_users_permission,
        edit_posts_permission
    ]

    chief_group, created = Group.objects.get_or_create(name='chief')
    chief_group.permissions = [
        edit_fines_permission,
        see_statistics_permission,
        edit_clubs_permission,
        edit_users_permission,
        edit_posts_permission
    ]

    coordinator_group, created = Group.objects.get_or_create(name='coordinator')
    employee_group, created = Group.objects.get_or_create(name='employee')


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_permissions),
    ]
