# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0002_auto_20160519_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='lastname',
        ),
        migrations.AddField(
            model_name='extuser',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='extuser',
            name='surname',
            field=models.CharField(default='', max_length=40, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
