# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0004_auto_20160520_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='additional_phone',
            field=models.CharField(default=2, max_length=30, verbose_name='Доп. телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extuser',
            name='gender',
            field=models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской')], default='female', max_length=10, verbose_name='Пол'),
        ),
    ]
