# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0005_auto_20160521_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Доп. телефон'),
        ),
    ]
