# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0009_auto_20160526_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID из старой системы'),
        ),
    ]
