# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 11:12
from __future__ import unicode_literals

from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def init_permissions(apps, schema_editor):
    ExtUser = apps.get_model("extuser", "ExtUser")
    ct = ContentType.objects.get_for_model(ExtUser)

    edit_reports_transfers_permission, created = Permission.objects.get_or_create(
        codename='can_edit_report_transfer', name='Редактирование переводов для сотрудника', content_type=ct
    )
    director_group = Group.objects.get(name='director')
    director_group.permissions.add(edit_reports_transfers_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0011_auto_20160609_2044'),
    ]

    operations = [
        migrations.RunPython(init_permissions),
    ]
