# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0011_auto_20160527_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extuser',
            name='pay_to_coord',
            field=models.BooleanField(default=False, verbose_name='Платить координатору'),
        ),
        migrations.AddField(
            model_name='extuser',
            name='pledge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Залог'),
        ),
    ]
