# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0012_add_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('num', models.PositiveSmallIntegerField(default=0, verbose_name='Номер')),
                ('dismissal', models.BooleanField(default=False, verbose_name='Возможно увольнение')),
            ],
            options={
                'ordering': ('num',),
            },
        ),
        migrations.AlterModelOptions(
            name='extuser',
            options={'ordering': ('surname',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
