# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20160630_1759'),
        ('extuser', '0013_auto_20160630_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPenaltySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('schedule', 'График'), ('report', 'Отчеты')], max_length=10, verbose_name='Тип')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.DayOfWeek', verbose_name='День недели')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
