# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0014_mainpenaltyschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpenaltyschedule',
            name='day_of_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.DayOfWeek', verbose_name='День недели'),
        ),
    ]
