# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0015_auto_20160630_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpenaltyschedule',
            name='start_week',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала недели за которую написан перевод'),
        ),
    ]
