# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0021_add_permissions_manage_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpenaltyschedule',
            name='day_of_week',
        ),
        migrations.DeleteModel(
            name='PenaltyType',
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ('-modified',)},
        ),
        migrations.DeleteModel(
            name='MainPenaltySchedule',
        ),
    ]
