# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 05:52
from __future__ import unicode_literals

from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def init_permissions(apps, schema_editor):
    ExtUser = apps.get_model("extuser", "ExtUser")

    edit_user_permission = Permission.objects.get(codename='can_edit_users')

    coordinator_group = Group.objects.get(name='coordinator')
    coordinator_group.permissions.add(edit_user_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0023_permission_special_stats'),
    ]

    operations = [
        migrations.RunPython(init_permissions),
    ]
